# -*- mode: python ; coding: utf-8 -*-
import sys
import os as os_mod
from pathlib import Path

block_cipher = None

project_root = os_mod.getcwd()

a = Analysis(
    ['gui_formatter.py'],
    pathex=[project_root],
    binaries=[],
    datas=[
        (os_mod.path.join('configs', 'active', 'config.yaml'), 'configs/active'),
        (os_mod.path.join('configs', 'active', 'config.json'), 'configs/active'),
        (os_mod.path.join('configs', 'active', 'config_v3.2.yaml'), 'configs/active'),
        (os_mod.path.join('configs', 'active', 'config_v4.2.yaml'), 'configs/active'),
        (os_mod.path.join('configs', 'includes', 'base_styles.yaml'), 'configs/includes'),
        (os_mod.path.join('configs', 'includes', 'page_setup_gost.yaml'), 'configs/includes'),
        (os_mod.path.join('configs', 'includes', 'main_config.yaml'), 'configs/includes'),
    ],
    hiddenimports=[
        'src', 'src.core', 'src.gui', 'src.apply', 'src.audit',
        'src.core.audit_engine', 'src.core.config_loader', 'src.core.document_model',
        'src.core.docx_utils', 'src.core.highlight_engine', 'src.core.main_controller',
        'src.core.optimized_application', 'src.core.page_manager', 'src.core.report_manager',
        'src.core.style_manager',
        'src.core.template_extractor', 'src.core.content_processor',
        'src.core.document_formatter', 'src.core.formatter_errors',
        'src.core.yaml_includes', 'src.core.snapshot_testing', 'src.core.cli',
        'src.config_editor', 'src.config_editor.dialog', 'src.config_editor.model',
        'src.config_editor.validators', 'src.config_editor.yaml_utils',
        'src.config_editor.field_widgets', 'src.config_editor.style_preview',
        'src.config_editor.tree_panel', 'src.config_editor.editor_panel',
        'src.gui.actions', 'src.gui.file_handlers', 'src.gui.main_window', 'src.gui.table_manager',
        'src.apply.apply_orchestrator', 'src.apply.base_applier', 'src.apply.font_applier',
        'src.apply.header_footer_applier', 'src.apply.paragraph_applier', 'src.apply.table_applier',
        'src.apply.style_applier',
        'src.audit.base_auditor', 'src.audit.font_auditor', 'src.audit.paragraph_auditor',
        'md_to_docx',
        'yaml', 'docx', 'docx.shared', 'docx.enum.text', 'docx.enum.style', 'docx.enum.table',
        'docx.enum.section', 'docx.oxml', 'docx.oxml.ns', 'docx.oxml.table', 'docx.opc.constants',
        'lxml', 'lxml.etree', 'lxml.objectify',
        'ttkthemes', 'ttkthemes.themed_tk',
        'networkx', 'networkx.algorithms', 'networkx.algorithms.dag',
        'networkx.algorithms.shortest_paths', 'networkx.algorithms.shortest_paths.generic',
        'networkx.algorithms.components', 'networkx.algorithms.components.connected',
        'networkx.classes', 'networkx.classes.function', 'networkx.classes.graph',
        'networkx.classes.digraph', 'networkx.convert', 'networkx.readwrite',
        'networkx.readwrite.json_graph', 'networkx.generators', 'networkx.generators.small',
        'networkx.utils', 'networkx.utils.decorators', 'networkx.exception',
        'ctypes', 'ctypes.util',
        'tkinter', 'tkinter.ttk', 'tkinter.filedialog', 'tkinter.messagebox',
        'tkinter.scrolledtext', 'tkinter.simpledialog', 'tkinter.font',
        'threading', 'queue', 'json', 're', 'os', 'sys', 'pathlib', 'logging', 'datetime',
        'copy', 'math', 'collections', 'itertools', 'functools', 'traceback', 'textwrap',
        'glob', 'shutil', 'tempfile', 'subprocess', 'webbrowser', 'hashlib', 'base64',
        'io', 'csv', 'string', 'uuid', 'inspect', 'pkgutil', 'importlib',
        'importlib.metadata', 'importlib.resources',
        'xml', 'xml.etree', 'xml.etree.ElementTree', 'html', 'html.parser',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5', 'PyQt6', 'PySide2', 'PySide6',
        'matplotlib', 'scipy', 'pandas', 'numpy',
        'PIL', 'Pillow',
        'notebook', 'jupyter', 'ipython',
        'tensorflow', 'torch', 'keras',
        'flask', 'django', 'fastapi',
        'bottle', 'cherrypy', 'tornado',
        'sphinx', 'docutils',
        'setuptools', 'pip', 'wheel',
        'cryptography', 'OpenSSL',
        'zmq', 'pyzmq',
        'sqlalchemy', 'alembic',
        'bokeh', 'plotly', 'dash',
        'nltk', 'spacy', 'sklearn',
        'cv2', 'opencv',
        'soundfile', 'sounddevice', 'pyaudio',
        'tqdm', 'colorama', 'rich',
        'requests', 'urllib3', 'httpx',
        'aiohttp', 'aiofiles', 'asyncio',
        'pytest', 'unittest',
        'test',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DemographicsFormatter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
